const sharedProduct = {
  price: 490,
  currency: "MAD",
  color: "Ecru",
  sizes: ["S", "M", "L", "XL"],
  details: ["Coupe decontractee", "Coton premium 240 gsm", "Impression graphique avant et dos"]
};

function makeProduct(id, city, description) {
  return {
    id: `morocco-${id}-tee`,
    name: `Morocco ${city} T-shirt`,
    ...sharedProduct,
    description
  };
}

window.ZELLIJ_CITIES = [
  {
    id: "casablanca",
    name: "Casablanca",
    arabic: "\u0627\u0644\u062f\u0627\u0631 \u0627\u0644\u0628\u064a\u0636\u0627\u0621",
    region: "Atlantique urbain",
    mood: "blanc, vert profond, orange coucher de soleil",
    palette: ["#0f4b3d", "#e7ded1", "#c86436"],
    status: "Disponible",
    image: "assets/products/casablanca-tee.png",
    photo: "assets/cities/casablanca.jpg",
    pageTitle: "La ville blanche, l'energie qui ne dort jamais.",
    pageDescription: "Casablanca represente le Maroc moderne: business, ocean, mosquee Hassan II et rythme urbain. Pour ZELLYJ, c'est la ville du depart, celle qui transforme la fierte culturelle en piece forte du quotidien.",
    product: makeProduct("casablanca", "Casablanca", "T-shirt ecru avec visuel Casablanca au dos, logo ZELLYJ au col et impression coeur cote face."),
    story: "La ville blanche, le rythme urbain et l'architecture iconique. Une piece forte pour ceux qui portent Casablanca comme une energie."
  },
  {
    id: "essaouira",
    name: "Essaouira",
    arabic: "\u0627\u0644\u0635\u0648\u064a\u0631\u0629",
    region: "Vent, remparts, Atlantique",
    mood: "bleu ocean, pierre claire, bois chaud",
    palette: ["#1c6d7a", "#f3f0e9", "#b17443"],
    status: "Disponible",
    image: "assets/products/essaouira-tee.png",
    photo: "assets/cities/essaouira.jpg",
    pageTitle: "La ville du vent, libre et lumineuse.",
    pageDescription: "Essaouira apporte une energie plus douce: remparts, ocean, musique, artisans et horizon. La capsule sent la liberte, le bleu sale de la mer et la chaleur du bois des anciennes ruelles.",
    product: makeProduct("essaouira", "Essaouira", "T-shirt ecru avec remparts, vagues atlantiques et soleil chaud pour une capsule libre et lumineuse."),
    story: "Une capsule pensee autour du vent, des remparts et de l'esprit libre de la cote."
  },
  {
    id: "tanger",
    name: "Tanger",
    arabic: "\u0637\u0646\u062c\u0629",
    region: "Mediterranee, passage, nuit",
    mood: "bleu nuit, blanc portuaire, rouge signal",
    palette: ["#183b59", "#f6f4ee", "#bf3f32"],
    status: "Disponible",
    image: "assets/products/tanger-tee.png",
    photo: "assets/cities/tanger.jpg",
    pageTitle: "La porte du nord, entre deux mers.",
    pageDescription: "Tanger est une ville de passage et de melange: port, falaise, cafe, voyage et mouvement. ZELLYJ la traduit comme une capsule ouverte sur le monde, elegante et un peu nocturne.",
    product: makeProduct("tanger", "Tanger", "T-shirt ecru inspire du phare, de la cote et de l'esprit voyageur de Tanger."),
    story: "Tanger comme point de passage: Europe, Afrique, mer et mouvement."
  },
  {
    id: "kettama",
    name: "Kettama",
    arabic: "\u0643\u062a\u0627\u0645\u0629",
    region: "Rif, montagne, brume",
    mood: "vert foret, brume, terre sombre",
    palette: ["#234b37", "#dfe7df", "#6a5540"],
    status: "Disponible",
    image: "assets/products/kettama-tee.png",
    photo: "assets/cities/kettama.jpg",
    pageTitle: "Le Rif profond, calme et mysterieux.",
    pageDescription: "Kettama porte une autre image du Maroc: montagne, vert intense, silence, terre et relief. C'est une rubrique plus brute, plus organique, construite autour de la nature et de la memoire du Rif.",
    product: makeProduct("kettama", "Kettama", "T-shirt ecru avec paysage du Rif, verts profonds et composition organique."),
    story: "Une ville-rubrique plus mystique, construite autour du Rif, du relief et de la nature."
  },
  {
    id: "fes",
    name: "Fes",
    arabic: "\u0641\u0627\u0633",
    region: "Medina, savoir-faire, heritage",
    mood: "vert zellige, cuivre, ivoire",
    palette: ["#0d5a47", "#bc7d3f", "#f7f1e6"],
    status: "Disponible",
    image: "assets/products/fes-tee.png",
    photo: "assets/cities/fes.jpg",
    pageTitle: "La capitale du detail et du savoir-faire.",
    pageDescription: "Fes, c'est l'artisanat, les portes monumentales, la medina et le geste transmis. Pour ZELLYJ, cette ville donne la profondeur: motifs, patience, heritage et precision graphique.",
    product: makeProduct("fes", "Fes", "T-shirt ecru avec porte monumentale, medina et accents cuivre pour l'heritage artisanal."),
    story: "Fes porte l'artisanat, le detail et la profondeur historique de la medina."
  },
  {
    id: "chaouenne",
    name: "Chefchaouen",
    arabic: "\u0634\u0641\u0634\u0627\u0648\u0646",
    region: "Bleu, ruelles, calme",
    mood: "bleu clair, indigo, blanc",
    palette: ["#4d9ac7", "#24456f", "#f5f7f5"],
    status: "Disponible",
    image: "assets/products/chaouenne-tee.png",
    photo: "assets/cities/chaouenne.jpg",
    pageTitle: "Le bleu calme qui reste en memoire.",
    pageDescription: "Chefchaouen donne a la collection une respiration: ruelles bleues, lumiere douce et silence visuel. C'est la capsule de l'apaisement, mais avec une presence immediate.",
    product: makeProduct("chaouenne", "Chefchaouen", "T-shirt ecru avec ruelles bleues, escaliers et lumiere douce du nord."),
    story: "Une capsule douce et tres visuelle autour du bleu, des ruelles et de la lumiere du nord."
  },
  {
    id: "rabat",
    name: "Rabat",
    arabic: "\u0627\u0644\u0631\u0628\u0627\u0637",
    region: "Capitale, lignes propres",
    mood: "vert institution, sable clair, rouge drapeau",
    palette: ["#174f43", "#e9dfcf", "#b93531"],
    status: "Disponible",
    image: "assets/products/rabat-tee.png",
    photo: "assets/cities/rabat.jpg",
    pageTitle: "La capitale calme, droite et elegante.",
    pageDescription: "Rabat est plus minimaliste: Tour Hassan, lignes nettes, institutions, jardins et ocean proche. Dans ZELLYJ, elle devient une capsule propre, equilibree et mature.",
    product: makeProduct("rabat", "Rabat", "T-shirt ecru avec Tour Hassan, lignes calmes et palette verte institutionnelle."),
    story: "Rabat est plus minimaliste: lignes nettes, capitale calme, culture institutionnelle."
  },
  {
    id: "agadir",
    name: "Agadir",
    arabic: "\u0623\u0643\u0627\u062f\u064a\u0631",
    region: "Soleil, plage, sud",
    mood: "jaune soleil, bleu plage, argile",
    palette: ["#d59a2f", "#2d7890", "#c96b3b"],
    status: "Disponible",
    image: "assets/products/agadir-tee.png",
    photo: "assets/cities/agadir.jpg",
    pageTitle: "Le sud solaire, simple et direct.",
    pageDescription: "Agadir apporte la lumiere, la plage et une energie plus sportive. C'est une ville facile a porter: chaude, positive, jeune, avec un imaginaire de vacances et de mouvement.",
    product: makeProduct("agadir", "Agadir", "T-shirt ecru avec baie d'Agadir, soleil du sud et relief de la kasbah."),
    story: "Une capsule chaude et solaire, pensee pour l'energie du sud et la vie de plage."
  },
  {
    id: "dakhla",
    name: "Dakhla",
    arabic: "\u0627\u0644\u062f\u0627\u062e\u0644\u0629",
    region: "Lagune, desert, horizon",
    mood: "turquoise, sable, bleu profond",
    palette: ["#1f9ba5", "#e4c88c", "#12344f"],
    status: "Disponible",
    image: "assets/products/dakhla-tee.png",
    photo: "assets/cities/dakhla.png",
    pageTitle: "La lagune, le desert et l'horizon.",
    pageDescription: "Dakhla donne une dimension internationale a ZELLYJ: kitesurf, lagune turquoise, sable et liberte. C'est la capsule du voyage, du sport et des grands espaces.",
    product: makeProduct("dakhla", "Dakhla", "T-shirt ecru avec lagune, kitesurf, palmiers et horizon desertique."),
    story: "Dakhla parle d'horizon, de sport, de lagune et de desert sans fin."
  },
  {
    id: "marrakech",
    name: "Marrakech",
    arabic: "\u0645\u0631\u0627\u0643\u0634",
    region: "Ocre, jardins, intensite",
    mood: "ocre rouge, vert jardin, or",
    palette: ["#b34f35", "#23533d", "#c59b4c"],
    status: "Disponible",
    image: "assets/products/marrakech-tee.png",
    photo: "assets/cities/marrakech.jpg",
    pageTitle: "L'ocre, les jardins et l'intensite.",
    pageDescription: "Marrakech est la capsule la plus chaude: Koutoubia, palmiers, jardins, ocre et energie. Elle parle aux touristes comme aux Marocains, avec une force visuelle immediate.",
    product: makeProduct("marrakech", "Marrakech", "T-shirt ecru avec Koutoubia, jardins, palmiers et chaleur ocre."),
    story: "Marrakech est la capsule la plus intense: ocre, jardin, chaleur et energie."
  },
  {
    id: "laayoune",
    name: "Laayoune",
    arabic: "\u0627\u0644\u0639\u064a\u0648\u0646",
    region: "Sahara, dunes, horizon",
    mood: "sable, vert profond, orange soleil",
    palette: ["#0f4b3d", "#d69752", "#c85f2f"],
    status: "Disponible",
    image: "assets/products/laayoune-tee.png",
    photo: "assets/cities/laayoune.jpg",
    pageTitle: "Le souffle du Sahara, fier et lumineux.",
    pageDescription: "Laayoune ajoute une energie saharienne a ZELLYJ: horizon large, sable chaud, palmiers et fierte du sud. Cette capsule parle de territoire, de calme puissant et de presence marocaine.",
    product: makeProduct("laayoune", "Laayoune", "T-shirt ecru avec dunes, horizon saharien et lumiere chaude du sud marocain."),
    story: "Laayoune ouvre la collection vers le Sahara: sable, horizon, fierte du sud et graphisme solaire."
  }
];
