window.ZELLIJ_CITIES = [
  {
    id: "casablanca",
    name: "Casablanca",
    arabic: "\u0627\u0644\u062f\u0627\u0631 \u0627\u0644\u0628\u064a\u0636\u0627\u0621",
    region: "Atlantique urbain",
    mood: "blanc, vert profond, orange coucher de soleil",
    palette: ["#0f4b3d", "#e7ded1", "#c86436"],
    status: "Disponible",
    image: "assets/morocco-casablanca-tee.png",
    photo: "assets/cities/casablanca.jpg",
    pageTitle: "La ville blanche, l'energie qui ne dort jamais.",
    pageDescription: "Casablanca represente le Maroc moderne: business, ocean, mosquee Hassan II et rythme urbain. Pour ZELLIJ, c'est la ville du depart, celle qui transforme la fierte culturelle en piece forte du quotidien.",
    product: {
      id: "morocco-casablanca-tee",
      name: "Morocco Casablanca T-shirt",
      price: 490,
      currency: "MAD",
      color: "Ecru",
      sizes: ["S", "M", "L", "XL"],
      description: "T-shirt ecru avec visuel Casablanca au dos, logo ZELLIJ au col et impression coeur cote face.",
      details: ["Coupe decontractee", "Coton premium 240 gsm", "Impression graphique avant et dos"]
    },
    story: "La ville blanche, le rythme urbain et l'architecture iconique. Le premier produit ZELLIJ rend hommage a Casablanca avec un visuel dos fort et une signature discrete cote coeur."
  },
  {
    id: "essaouira",
    name: "Essaouira",
    arabic: "\u0627\u0644\u0635\u0648\u064a\u0631\u0629",
    region: "Vent, remparts, Atlantique",
    mood: "bleu ocean, pierre claire, bois chaud",
    palette: ["#1c6d7a", "#f3f0e9", "#b17443"],
    status: "Photos ajoutees",
    photo: "assets/cities/essaouira.jpg",
    pageTitle: "La ville du vent, libre et lumineuse.",
    pageDescription: "Essaouira apporte une energie plus douce: remparts, ocean, musique, artisans et horizon. La capsule doit sentir la liberte, le bleu sale de la mer et la chaleur du bois des anciennes ruelles.",
    story: "Une capsule pensee autour du vent, des remparts et de l'esprit libre de la cote."
  },
  {
    id: "tanger",
    name: "Tanger",
    arabic: "\u0637\u0646\u062c\u0629",
    region: "Mediterranee, passage, nuit",
    mood: "bleu nuit, blanc portuaire, rouge signal",
    palette: ["#183b59", "#f6f4ee", "#bf3f32"],
    status: "Photos ajoutees",
    photo: "assets/cities/tanger.jpg",
    pageTitle: "La porte du nord, entre deux mers.",
    pageDescription: "Tanger est une ville de passage et de melange: port, falaise, cafe, voyage et mouvement. ZELLIJ la traduit comme une capsule ouverte sur le monde, elegante et un peu nocturne.",
    story: "Tanger comme point de passage: europe, afrique, mer et mouvement."
  },
  {
    id: "kettama",
    name: "Kettama",
    arabic: "\u0643\u062a\u0627\u0645\u0629",
    region: "Rif, montagne, brume",
    mood: "vert foret, brume, terre sombre",
    palette: ["#234b37", "#dfe7df", "#6a5540"],
    status: "Photos ajoutees",
    photo: "assets/cities/kettama.jpg",
    pageTitle: "Le Rif profond, calme et mysterieux.",
    pageDescription: "Kettama porte une autre image du Maroc: montagne, vert intense, silence, terre et relief. C'est une rubrique plus brute, plus organique, construite autour de la nature et de la memoire du Rif.",
    story: "Une ville-rubrique plus mystique, construite autour du Rif, du relief et de la nature."
  },
  {
    id: "fes",
    name: "Fes",
    arabic: "\u0641\u0627\u0633",
    region: "Medina, savoir-faire, heritage",
    mood: "vert zellige, cuivre, ivoire",
    palette: ["#0d5a47", "#bc7d3f", "#f7f1e6"],
    status: "Photos ajoutees",
    photo: "assets/cities/fes.jpg",
    pageTitle: "La capitale du detail et du savoir-faire.",
    pageDescription: "Fes, c'est l'artisanat, les portes monumentales, la medina et le geste transmis. Pour ZELLIJ, cette ville donne la profondeur: motifs, patience, heritage et precision graphique.",
    story: "Fes portera l'artisanat, le detail et la profondeur historique de la medina."
  },
  {
    id: "chaouenne",
    name: "Chaouenne",
    arabic: "\u0634\u0641\u0634\u0627\u0648\u0646",
    region: "Bleu, ruelles, calme",
    mood: "bleu clair, indigo, blanc",
    palette: ["#4d9ac7", "#24456f", "#f5f7f5"],
    status: "Photos ajoutees",
    photo: "assets/cities/chaouenne.jpg",
    pageTitle: "Le bleu calme qui reste en memoire.",
    pageDescription: "Chaouenne donne a la collection une respiration: ruelles bleues, lumiere douce et silence visuel. C'est la capsule de l'apaisement, mais avec une presence immediate.",
    story: "Une capsule douce et tres visuelle autour du bleu, des ruelles et de la lumiere du nord."
  },
  {
    id: "rabat",
    name: "Rabat",
    arabic: "\u0627\u0644\u0631\u0628\u0627\u0637",
    region: "Capitale, lignes propres",
    mood: "vert institution, sable clair, rouge drapeau",
    palette: ["#174f43", "#e9dfcf", "#b93531"],
    status: "Photos ajoutees",
    photo: "assets/cities/rabat.jpg",
    pageTitle: "La capitale calme, droite et elegante.",
    pageDescription: "Rabat est plus minimaliste: Tour Hassan, lignes nettes, institutions, jardins et ocean proche. Dans ZELLIJ, elle devient une capsule propre, equilibree et mature.",
    story: "Rabat sera plus minimaliste: lignes nettes, capitale calme, culture institutionnelle."
  },
  {
    id: "agadir",
    name: "Agadir",
    arabic: "\u0623\u0643\u0627\u062f\u064a\u0631",
    region: "Soleil, plage, sud",
    mood: "jaune soleil, bleu plage, argile",
    palette: ["#d59a2f", "#2d7890", "#c96b3b"],
    status: "Photos ajoutees",
    photo: "assets/cities/agadir.jpg",
    pageTitle: "Le sud solaire, simple et direct.",
    pageDescription: "Agadir apporte la lumiere, la plage et une energie plus sportive. C'est une ville facile a porter: chaude, positive, jeune, avec un imaginaire de vacances et de mouvement.",
    story: "Une capsule chaude et solaire, pensee pour l'energie du sud et la vie de plage."
  },
  {
    id: "dakhla",
    name: "Dakhla",
    arabic: "\u0627\u0644\u062f\u0627\u062e\u0644\u0629",
    region: "Lagune, desert, horizon",
    mood: "turquoise, sable, bleu profond",
    palette: ["#1f9ba5", "#e4c88c", "#12344f"],
    status: "Photos ajoutees",
    photo: "assets/cities/dakhla.png",
    pageTitle: "La lagune, le desert et l'horizon.",
    pageDescription: "Dakhla donne une dimension internationale a ZELLIJ: kitesurf, lagune turquoise, sable et liberte. C'est la capsule du voyage, du sport et des grands espaces.",
    story: "Dakhla parlera d'horizon, de sport, de lagune et de desert sans fin."
  },
  {
    id: "marrakech",
    name: "Marrakech",
    arabic: "\u0645\u0631\u0627\u0643\u0634",
    region: "Ocre, jardins, intensite",
    mood: "ocre rouge, vert jardin, or",
    palette: ["#b34f35", "#23533d", "#c59b4c"],
    status: "Photos ajoutees",
    photo: "assets/cities/marrakech.jpg",
    pageTitle: "L'ocre, les jardins et l'intensite.",
    pageDescription: "Marrakech est la capsule la plus chaude: Koutoubia, palmiers, jardins, ocre et energie. Elle parle aux touristes comme aux Marocains, avec une force visuelle immediate.",
    story: "Marrakech sera la capsule la plus intense: ocre, jardin, chaleur et energie."
  }
];
